include(core/BreakingEngine-core.pri)
include(rendering/BreakingEngine-rendering.pri)
include(io/BreakingEngine-io.pri)
include(opengl/BreakingEngine-opengl.pri)
include(physics/BreakingEngine-physics.pri)
include(tools/BreakingEngine-tools.pri)
